
###
PUT  /api/posts/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjgwMDg4OTAyLCJpYXQiOjE2ODAwODgzMDIsImp0aSI6ImNjMTIxNTU4ZWYzZDQyNzZhZjBkOWJmZmFjNzcyZTllIiwidXNlcl9pZCI6NX0.CnDy5agVU9_r-R-jRmZ2G9bSodvmesoBRZCE7W-9eek 
Host: 127.0.0.1:8000

Content-Type: application/json
{
  "title": "test updated"
}

###


GET /api/posts/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjgwMDg4OTAyLCJpYXQiOjE2ODAwODgzMDIsImp0aSI6ImNjMTIxNTU4ZWYzZDQyNzZhZjBkOWJmZmFjNzcyZTllIiwidXNlcl9pZCI6NX0.CnDy5agVU9_r-R-jRmZ2G9bSodvmesoBRZCE7W-9eek
Host: 127.0.0.1:8000

Content-Type: "application/json"


{
  "title": "test updated"
}



###
POST /api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}
