GET  /api/posts/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjgwMzMxMDk4LCJpYXQiOjE2ODAzMzA3NDgsImp0aSI6IjYzNTk0ZWViNWFiMjQyZThiOWQ0MTNkZTNkNjBjMWRkIiwidXNlcl9pZCI6MSwiaWQiOjEsInVzZXJuYW1lIjoibmFyYSIsImlzX3N1cGVydXNlciI6dHJ1ZX0.w08L8UM4ZFh4WIrBZMFIA2UWt7uturQEqZeCpBMgo-4 
Host: 127.0.0.1:8000

Content-Type: application/json
{
  "title": "test updated"
}

