GET  /api/posts/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjgwMjU0NTM0LCJpYXQiOjE2ODAyNTQyMzQsImp0aSI6IjFlOWViODBiYjRjZTQzMmM5NjAzM2Y3YWFjMjNkOGU5IiwidXNlcl9pZCI6MSwiaWQiOjEsInVzZXJuYW1lIjoibmFyYSIsImlzX3N1cGVydXNlciI6dHJ1ZX0.w4l1Sq0Db_yVj_9hQ3PbMbDIjXMPYr6Npca04REDQBE 
Host: 127.0.0.1:8000

Content-Type: application/json
{
  "title": "test updated"
}

